/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Model = (props) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('./models/animals/ShibaInu.gltf')
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        if (actions) {
            actions['Walk']?.play()
        }
    }, [actions])


    return (
        <group
            ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="AnimalArmature">
                    <group name="ShibaInu">
                        <skinnedMesh
                            name="Cube"
                            geometry={nodes.Cube.geometry}
                            material={materials.Main}
                            skeleton={nodes.Cube.skeleton}
                        />
                        <skinnedMesh
                            name="Cube_1"
                            geometry={nodes.Cube_1.geometry}
                            material={materials.Black}
                            skeleton={nodes.Cube_1.skeleton}
                        />
                        <skinnedMesh
                            name="Cube_2"
                            geometry={nodes.Cube_2.geometry}
                            material={materials.Main_Light}
                            skeleton={nodes.Cube_2.skeleton}
                        />
                        <skinnedMesh
                            name="Cube_3"
                            geometry={nodes.Cube_3.geometry}
                            material={materials.Eyes_Black}
                            skeleton={nodes.Cube_3.skeleton}
                        />
                        <skinnedMesh
                            name="Cube_4"
                            geometry={nodes.Cube_4.geometry}
                            material={materials.Eyes_White}
                            skeleton={nodes.Cube_4.skeleton}
                        />
                        <skinnedMesh
                            name="Cube_5"
                            geometry={nodes.Cube_5.geometry}
                            material={materials.Eyes_Pupil}
                            skeleton={nodes.Cube_5.skeleton}
                        />
                    </group>
                    <primitive object={nodes.Body} />
                    <primitive object={nodes.IKBackLegL} />
                    <primitive object={nodes.IKFrontLegL} />
                    <primitive object={nodes.IKBackLegR} />
                    <primitive object={nodes.IKFrontLegR} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('./models/animals/ShibaInu.gltf')

export default Model
